### ISSUE TITLE
BE: Error deleting order

### ISSUE THREAD

**Issue by kolodgeeva** [Autopartner/autopartner-service#66]
During deleting the order I got an error
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/2835251/229569326-bbd54ddb-44cc-47e8-81a6-4c7b0b2bee0d.png">
@demesup could you pls create several orders with tasks and without and try to delete them on your local and confirm do you have an error?
If yes, pls fix it.

**Comment by demesup** [comment]
Everything seems to be working fine no matter how many orders /tasks there are.

**Comment by demesup** [comment]
![image](https://user-images.githubusercontent.com/100019943/229771566-040af3cd-c59a-474e-9f03-6939dd759452.png)
I tried adding this, but I don't know whether it will work since I don;t have this excpetion

**Comment by kolodgeeva** [comment]
Hi! @demesup got it, let me clear the DB on the server. Maybe we have outdated db

**Comment by kolodgeeva** [comment]
Hi! @demesup pls change the way we fetch order tasks. From lazy fetch to fetch join
