### ISSUE TITLE
BE: Swagger UI. Get all orders without params is not allowed.

### ISSUE THREAD

**Issue by kolodgeeva** [Autopartner/autopartner-service#67]
@demesup could you pls take a look why get all orders without params is not allowed from Swagger UI

![Image](https://user-images.githubusercontent.com/2835251/229774959-89132b9f-aa14-4bca-bc11-a5ada0d83a22.png)

**Comment by demesup** [comment]
![image](https://user-images.githubusercontent.com/100019943/230316254-daad282b-4aff-4461-893a-887fd2976031.png)
![image](https://user-images.githubusercontent.com/100019943/230316355-512eaa72-1610-4bd1-bccb-5df8dfcef768.png)
![image](https://user-images.githubusercontent.com/100019943/230316447-f1422e80-a824-45ad-a733-580df3b7f258.png)
The same problem was in these endpoints too

**Comment by kolodgeeva** [comment]
thank @demesup ! looks like Optional for swagger is not enough
