### ISSUE TITLE
BE: Implement Product Events and Product State

### ISSUE THREAD

**Issue by kolodgeeva** [Autopartner/autopartner-service#76]
Event Sourcing

Для того щоб мати представлення яка кількість продукту у нас є на складі, нам треба враховувави поставки (як прихід товару, так і повернення його постачальнику) і використання продукту в замовленнях (додавання в замовлення, видалення з замовлення).
Редагувати поле quantity у продукта - погана ідея, бо прийде момент, коли це значення зіб’ється і данні будуть не консистенті. Наприклад сталась якась помилка і тепер ми не знаємо скільки продукту реально є на складі. 

Одне з рішень це Event Sourcing 
https://medium.com/@tobyhede/event-sourcing-with-postgresql-28c5e8f211a2
https://softwaremill.com/implementing-event-sourcing-using-a-relational-database/
https://martendb.io/events/

Завдяки цьому рішенню ми можемо мати повну історію, що відбувалось з продуктом і на базі цієї історії вираховувати скільки продукту є на складі

Product Events:
ProductAddedEvent (quantity)
ProductReturnedEvent (quantity) - може бути повернутий частково
ProductAddedToOrderEvent (quantity) 
ProductRemovedFromOrderEvent (quantity) - може бути повернутий частково

**Comment by kolodgeeva** [comment]
@demesup 1 step: describe a solution - diagram, text. Investigate possible solutions. Follow KIS (keep it simple) principle

**Comment by demesup** [comment]
https://medium.com/@tobyhede/event-sourcing-with-postgresql-28c5e8f211a2

table product_state_events(or just events)
columns:
id, 
vendor_code(if we are not going to use event sourcing with any other entity type)
event_type(enum)
body(jsonb)
created_at
user_id(if we want to know who made changes)

We can create ProductStateService.checkQuantity(vendorCode, requestedQuantity)

We can also create event Snapshot to avoid counting productState each time from the very beginning

**Comment by kolodgeeva** [comment]
Hi! @demesup 
the table can be just product_events
user_id will be helpful

Snapshot is ok

All logic should be on the backend side, not db
BD just stores events

We can start with a simple version:
- store events
- calculate the state every time it's needed

When this model is working fine, we can introduce Snapshot

But if you feel good to implement Snapshot from scratch I'm ok with that
Just describe here how you are going to implement everything (feature design) - classes, methods

For reference:
https://blog.knoldus.com/event-sourcing-with-springboot/
https://www.baeldung.com/cqrs-event-sourcing-java (CQRS is not required)
